#!/bin/sh

. /opt/drupal-7.56-3/scripts/setenv.sh
SASL_PATH="/opt/drupal-7.56-3/common/lib/sasl2"
                export SASL_PATH
exec /opt/drupal-7.56-3/common/sbin/.testsaslauthd.bin -f "/opt/drupal-7.56-3/common/etc/sasldb2" "$@"
